[package]
name = "yzix-store-refs"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 WITH LLVM-exception"

[dependencies]
camino = "1.0"
store-ref-scanner = "0.1"
tracing = "0.1"

[dependencies.yzix-store]
path = "../yzix-store"
