[package]
name = "yzix-client"
version = "0.2.0"
edition = "2021"

[dependencies]
bytes = "1.7"
reqwest.workspace = true
serde_json = "1.0"
tracing.workspace = true

[dependencies.yzix-core]
path = "../yzix-core"
