[package]
name = "yzix-client"
version = "0.2.0"
edition = "2021"

[dependencies]
bytes = "1.7"
serde_json = "1.0"
tracing = "0.1"

[dependencies.reqwest]
version = "0.11"
default-features = false
features = [
  "json"
]

[dependencies.yzix-core]
path = "../yzix-core"
