[package]
name = "yzix-ser-trait"
description = "Serialization trait, designed to be portable comparable (in contrast to std::hash::Hash)"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 WITH LLVM-exception"

[dependencies]

[dependencies.digest]
version = "0.10"
default-features = false
