[package]
name = "yzix-strwrappers"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]

[dependencies.serde]
version = "1.0"
default-features = false
features = ["alloc", "derive"]
