[package]
name = "yzix-server"
description = "Yzix server executable, wraps the store-builder task"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 WITH LLVM-exception"

[dependencies]
num_cpus = "1.13"
serde = "1.0"
toml = "0.5"
tracing = "0.1"
tracing-subscriber = "0.3"

[dependencies.futures-util]
version = "0.3"
features = ["sink"]

[dependencies.tokio]
version = "1.17"
features = [
  "io-util",
  "macros",
  "net",
  "rt",
  "rt-multi-thread",
  "signal",
  "sync"
]

[dependencies.yzix-proto]
path = "../yzix-proto"

[dependencies.yzix-store-builder]
path = "../yzix-store-builder"
